import { Body, Controller, HttpCode, HttpStatus, Param, ParseUUIDPipe, Post, UseGuards } from '@nestjs/common';
import { CurrentUser } from '../../../auth/decorators/current-user.decorator';
import { Permissions } from '../../../auth/decorators/permissions.decorator';
import { JwtAuthGuard } from '../../../auth/guards/jwt-auth.guard';
import { PermissionsGuard } from '../../../auth/guards/permissions.guard';
import { FinancialManagementUseCases } from '../../application/financial-management.use-cases';
import { CreateFinancialBankMatchRequestDto, CreateFinancialBankStatementLineRequestDto, CreateFinancialClaimSettlementRequestDto, CreateFinancialPostingRequestDto, CreateFinancialRecoveryRequestDto, CreateFinancialRemittanceBatchRequestDto, CreateFinancialRemittanceEvidenceRequestDto, CreateFinancialRemittanceLineItemRequestDto, CreateFinancialSettlementDeductionRequestDto } from '../dto/financial-command-request.dto';

@Controller('v1/organizations/:organizationId/hospitals/:hospitalId/financial')
@UseGuards(JwtAuthGuard, PermissionsGuard)
export class FinancialV1Controller {
  constructor(private readonly useCases: FinancialManagementUseCases) {}
  private scope(organizationId:string,hospitalId:string,actorUserId:string) { return { organizationId,hospitalId,actorUserId }; }
  @Post('remittance-batches') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createBatch(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialRemittanceBatchRequestDto) { const financialRemittanceBatchId=await this.useCases.createRemittanceBatch({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialRemittanceBatchId}; }
  @Post('remittance-line-items') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createLine(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialRemittanceLineItemRequestDto) { const financialRemittanceLineItemId=await this.useCases.createRemittanceLineItem({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialRemittanceLineItemId}; }
  @Post('remittance-evidence') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createEvidence(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialRemittanceEvidenceRequestDto) { const financialRemittanceEvidenceId=await this.useCases.createRemittanceEvidence({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialRemittanceEvidenceId}; }
  @Post('claim-settlements') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createSettlement(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialClaimSettlementRequestDto) { const financialClaimSettlementId=await this.useCases.createClaimSettlement({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialClaimSettlementId}; }
  @Post('settlement-deductions') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createDeduction(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialSettlementDeductionRequestDto) { const financialSettlementDeductionId=await this.useCases.createSettlementDeduction({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialSettlementDeductionId}; }
  @Post('recoveries') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createRecovery(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialRecoveryRequestDto) { const financialRecoveryId=await this.useCases.createRecovery({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialRecoveryId}; }
  @Post('postings') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createPosting(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialPostingRequestDto) { const financialPostingId=await this.useCases.createPosting({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialPostingId}; }
  @Post('bank-statement-lines') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createBankLine(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialBankStatementLineRequestDto) { const financialBankStatementLineId=await this.useCases.createBankStatementLine({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialBankStatementLineId}; }
  @Post('bank-matches') @HttpCode(HttpStatus.CREATED) @Permissions('financial.update') async createBankMatch(@Param('organizationId',ParseUUIDPipe) organizationId:string,@Param('hospitalId',ParseUUIDPipe) hospitalId:string,@CurrentUser('id') actorUserId:string,@Body() body:CreateFinancialBankMatchRequestDto) { const financialBankMatchId=await this.useCases.createBankMatch({...this.scope(organizationId,hospitalId,actorUserId),...body}); return {financialBankMatchId}; }
}
