import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';

import { FinancialClaimSettlement, FinancialSettlementDeduction } from '../domain/financial-claim-settlement.aggregate';
import { FinancialDomainError } from '../domain/financial-domain.error';
import { FinancialPosting } from '../domain/financial-posting';
import { FinancialRecovery } from '../domain/financial-recovery.aggregate';
import { FinancialRemittanceBatch, FinancialRemittanceEvidence, FinancialRemittanceLineItem } from '../domain/financial-remittance-batch.aggregate';
import { FinancialManagementRepository } from '../infrastructure/financial-management.repository';
import { FinancialAccessService } from './financial-access.service';

export interface FinancialCommandContext { actorUserId: string; organizationId: string; hospitalId: string; }
export interface CreateRemittanceBatchCommand extends FinancialCommandContext { insurancePartnerId: string; claimProductReferenceValueId: string; remittanceSourceTypeReferenceValueId: string; remittanceStatusReferenceValueId: string; remittanceReference: string; receivedAt: string; currencyCode: string; grossAmount: number; netAmount: number; externalReference?: string | null; notes?: string | null; }
export interface CreateRemittanceLineItemCommand extends FinancialCommandContext { financialRemittanceBatchId: string; claimId?: string | null; lineStatusReferenceValueId: string; payerClaimReference?: string | null; lineReference: string; grossAmount: number; deductionAmount: number; netAmount: number; currencyCode: string; receivedPayloadSummary?: string | null; }
export interface CreateRemittanceEvidenceCommand extends FinancialCommandContext { financialRemittanceBatchId: string; storageObjectReference: string; fileName: string; mimeType?: string | null; fileSizeBytes?: number | null; documentHash?: string | null; }
export interface CreateClaimSettlementCommand extends FinancialCommandContext { claimId: string; insurancePartnerId: string; financialRemittanceLineItemId?: string | null; claimProductReferenceValueId: string; settlementStatusReferenceValueId: string; settlementReference: string; payerSettlementReference?: string | null; settledAt: string; currencyCode: string; grossPayerPaidAmount: number; tdsAmount: number; payerDeductionAmount: number; otherPayerAdjustmentAmount: number; netPayerSettlementAmount: number; patientResponsibilityAmount: number; hospitalWriteOffAmount: number; notes?: string | null; }
export interface CreateSettlementDeductionCommand extends FinancialCommandContext { financialClaimSettlementId: string; deductionTypeReferenceValueId: string; deductionReference?: string | null; description?: string | null; amount: number; currencyCode: string; }
export interface CreateRecoveryCommand extends FinancialCommandContext { claimId: string; financialClaimSettlementId?: string | null; insurancePartnerId: string; claimProductReferenceValueId: string; recoveryTypeReferenceValueId: string; recoveryStatusReferenceValueId: string; recoveryReference: string; openedAt: string; dueAt?: string | null; currencyCode: string; originalAmount: number; recoveredAmount: number; outstandingAmount: number; notes?: string | null; }
export interface CreatePostingCommand extends FinancialCommandContext { claimId?: string | null; financialClaimSettlementId?: string | null; financialRecoveryId?: string | null; claimProductReferenceValueId: string; postingTypeReferenceValueId: string; postingReference: string; postingSequence: number; postedAt: string; currencyCode: string; debitAccountCode: string; creditAccountCode: string; amount: number; description?: string | null; }
export interface CreateBankStatementLineCommand extends FinancialCommandContext { bankTransactionReference: string; bankAccountReference: string; transactionAt: string; valueDate?: string | null; currencyCode: string; creditAmount: number; debitAmount: number; narration?: string | null; bankMatchStatusReferenceValueId: string; }
export interface CreateBankMatchCommand extends FinancialCommandContext { financialBankStatementLineId: string; financialRemittanceBatchId?: string | null; financialClaimSettlementId?: string | null; bankMatchStatusReferenceValueId: string; matchedAmount: number; matchedAt: string; notes?: string | null; }

@Injectable()
export class FinancialManagementUseCases {
  constructor(private readonly repository: FinancialManagementRepository, private readonly access: FinancialAccessService) {}

  async createRemittanceBatch(c: CreateRemittanceBatchCommand): Promise<string> {
    await this.allow(c); const id = randomUUID();
    this.domain(() => FinancialRemittanceBatch.create({ financialRemittanceBatchId: id, organizationId: c.organizationId, hospitalId: c.hospitalId, insurancePartnerId: c.insurancePartnerId, claimProductReferenceValueId: c.claimProductReferenceValueId, remittanceSourceTypeReferenceValueId: c.remittanceSourceTypeReferenceValueId, remittanceStatusReferenceValueId: c.remittanceStatusReferenceValueId, remittanceReference: c.remittanceReference, currencyCode: c.currencyCode, grossAmount: c.grossAmount, netAmount: c.netAmount, createdBy: c.actorUserId, updatedBy: c.actorUserId, version: 1 }));
    return this.command(() => this.repository.createRemittanceBatch({ p_financial_remittance_batch_id:id,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_insurance_partner_id:c.insurancePartnerId,p_claim_product_reference_value_id:c.claimProductReferenceValueId,p_remittance_source_type_reference_value_id:c.remittanceSourceTypeReferenceValueId,p_remittance_status_reference_value_id:c.remittanceStatusReferenceValueId,p_remittance_reference:c.remittanceReference,p_received_at:c.receivedAt,p_currency_code:c.currencyCode,p_gross_amount:c.grossAmount,p_net_amount:c.netAmount,p_external_reference:c.externalReference ?? null,p_notes:c.notes ?? null,p_actor_user_id:c.actorUserId }));
  }

  async createRemittanceLineItem(c: CreateRemittanceLineItemCommand): Promise<string> {
    await this.allow(c); const batch = await this.requireBatch(c); const id = randomUUID();
    this.domain(() => batch.addLineItem({ financialRemittanceLineItemId:id,financialRemittanceBatchId:c.financialRemittanceBatchId,organizationId:c.organizationId,hospitalId:c.hospitalId,lineReference:c.lineReference,lineStatusReferenceValueId:c.lineStatusReferenceValueId,grossAmount:c.grossAmount,deductionAmount:c.deductionAmount,netAmount:c.netAmount,currencyCode:c.currencyCode,version:1 } as FinancialRemittanceLineItem));
    return this.command(() => this.repository.createRemittanceLineItem({ p_financial_remittance_line_item_id:id,p_financial_remittance_batch_id:c.financialRemittanceBatchId,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_claim_id:c.claimId ?? null,p_line_status_reference_value_id:c.lineStatusReferenceValueId,p_payer_claim_reference:c.payerClaimReference ?? null,p_line_reference:c.lineReference,p_gross_amount:c.grossAmount,p_deduction_amount:c.deductionAmount,p_net_amount:c.netAmount,p_currency_code:c.currencyCode,p_received_payload_summary:c.receivedPayloadSummary ?? null,p_actor_user_id:c.actorUserId }));
  }

  async createRemittanceEvidence(c: CreateRemittanceEvidenceCommand): Promise<string> {
    await this.allow(c); const batch = await this.requireBatch(c); const id = randomUUID();
    this.domain(() => batch.addEvidence({ financialRemittanceEvidenceId:id,financialRemittanceBatchId:c.financialRemittanceBatchId,organizationId:c.organizationId,hospitalId:c.hospitalId,storageObjectReference:c.storageObjectReference,fileName:c.fileName,version:1 } as FinancialRemittanceEvidence));
    return this.command(() => this.repository.createRemittanceEvidence({ p_financial_remittance_evidence_id:id,p_financial_remittance_batch_id:c.financialRemittanceBatchId,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_storage_object_reference:c.storageObjectReference,p_file_name:c.fileName,p_mime_type:c.mimeType ?? null,p_file_size_bytes:c.fileSizeBytes ?? null,p_document_hash:c.documentHash ?? null,p_actor_user_id:c.actorUserId }));
  }

  async createClaimSettlement(c: CreateClaimSettlementCommand): Promise<string> {
    await this.allow(c); const id=randomUUID();
    this.domain(() => FinancialClaimSettlement.create({ financialClaimSettlementId:id,organizationId:c.organizationId,hospitalId:c.hospitalId,claimId:c.claimId,insurancePartnerId:c.insurancePartnerId,claimProductReferenceValueId:c.claimProductReferenceValueId,settlementStatusReferenceValueId:c.settlementStatusReferenceValueId,settlementReference:c.settlementReference,currencyCode:c.currencyCode,grossPayerPaidAmount:c.grossPayerPaidAmount,tdsAmount:c.tdsAmount,payerDeductionAmount:c.payerDeductionAmount,otherPayerAdjustmentAmount:c.otherPayerAdjustmentAmount,netPayerSettlementAmount:c.netPayerSettlementAmount,patientResponsibilityAmount:c.patientResponsibilityAmount,hospitalWriteOffAmount:c.hospitalWriteOffAmount,createdBy:c.actorUserId,updatedBy:c.actorUserId,version:1 }));
    return this.command(() => this.repository.createClaimSettlement({ p_financial_claim_settlement_id:id,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_claim_id:c.claimId,p_insurance_partner_id:c.insurancePartnerId,p_financial_remittance_line_item_id:c.financialRemittanceLineItemId ?? null,p_claim_product_reference_value_id:c.claimProductReferenceValueId,p_settlement_status_reference_value_id:c.settlementStatusReferenceValueId,p_settlement_reference:c.settlementReference,p_payer_settlement_reference:c.payerSettlementReference ?? null,p_settled_at:c.settledAt,p_currency_code:c.currencyCode,p_gross_payer_paid_amount:c.grossPayerPaidAmount,p_tds_amount:c.tdsAmount,p_payer_deduction_amount:c.payerDeductionAmount,p_other_payer_adjustment_amount:c.otherPayerAdjustmentAmount,p_net_payer_settlement_amount:c.netPayerSettlementAmount,p_patient_responsibility_amount:c.patientResponsibilityAmount,p_hospital_write_off_amount:c.hospitalWriteOffAmount,p_notes:c.notes ?? null,p_actor_user_id:c.actorUserId }));
  }

  async createSettlementDeduction(c: CreateSettlementDeductionCommand): Promise<string> {
    await this.allow(c); const settlement = await this.repository.findActiveSettlementById(c.organizationId,c.hospitalId,c.financialClaimSettlementId);
    if (!settlement) throw new NotFoundException('Claim Settlement was not found.'); const id=randomUUID();
    this.domain(() => settlement.addDeduction({ financialSettlementDeductionId:id,financialClaimSettlementId:c.financialClaimSettlementId,organizationId:c.organizationId,hospitalId:c.hospitalId,deductionTypeReferenceValueId:c.deductionTypeReferenceValueId,amount:c.amount,currencyCode:c.currencyCode,version:1 } as FinancialSettlementDeduction));
    return this.command(() => this.repository.createSettlementDeduction({ p_financial_settlement_deduction_id:id,p_financial_claim_settlement_id:c.financialClaimSettlementId,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_deduction_type_reference_value_id:c.deductionTypeReferenceValueId,p_deduction_reference:c.deductionReference ?? null,p_description:c.description ?? null,p_amount:c.amount,p_currency_code:c.currencyCode,p_actor_user_id:c.actorUserId }));
  }

  async createRecovery(c: CreateRecoveryCommand): Promise<string> { await this.allow(c); const id=randomUUID(); this.domain(() => FinancialRecovery.create({ financialRecoveryId:id,organizationId:c.organizationId,hospitalId:c.hospitalId,claimId:c.claimId,insurancePartnerId:c.insurancePartnerId,claimProductReferenceValueId:c.claimProductReferenceValueId,recoveryTypeReferenceValueId:c.recoveryTypeReferenceValueId,recoveryStatusReferenceValueId:c.recoveryStatusReferenceValueId,recoveryReference:c.recoveryReference,currencyCode:c.currencyCode,originalAmount:c.originalAmount,recoveredAmount:c.recoveredAmount,outstandingAmount:c.outstandingAmount,createdBy:c.actorUserId,updatedBy:c.actorUserId,version:1 })); return this.command(() => this.repository.createRecovery({ p_financial_recovery_id:id,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_claim_id:c.claimId,p_financial_claim_settlement_id:c.financialClaimSettlementId ?? null,p_insurance_partner_id:c.insurancePartnerId,p_claim_product_reference_value_id:c.claimProductReferenceValueId,p_recovery_type_reference_value_id:c.recoveryTypeReferenceValueId,p_recovery_status_reference_value_id:c.recoveryStatusReferenceValueId,p_recovery_reference:c.recoveryReference,p_opened_at:c.openedAt,p_due_at:c.dueAt ?? null,p_currency_code:c.currencyCode,p_original_amount:c.originalAmount,p_recovered_amount:c.recoveredAmount,p_outstanding_amount:c.outstandingAmount,p_notes:c.notes ?? null,p_actor_user_id:c.actorUserId })); }

  async createPosting(c: CreatePostingCommand): Promise<string> { await this.allow(c); const id=randomUUID(); this.domain(() => FinancialPosting.create({ financialPostingId:id,organizationId:c.organizationId,hospitalId:c.hospitalId,claimProductReferenceValueId:c.claimProductReferenceValueId,postingTypeReferenceValueId:c.postingTypeReferenceValueId,postingReference:c.postingReference,postingSequence:c.postingSequence,currencyCode:c.currencyCode,debitAccountCode:c.debitAccountCode,creditAccountCode:c.creditAccountCode,amount:c.amount,createdBy:c.actorUserId,updatedBy:c.actorUserId,version:1 })); return this.command(() => this.repository.createPosting({ p_financial_posting_id:id,p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_claim_id:c.claimId ?? null,p_financial_claim_settlement_id:c.financialClaimSettlementId ?? null,p_financial_recovery_id:c.financialRecoveryId ?? null,p_claim_product_reference_value_id:c.claimProductReferenceValueId,p_posting_type_reference_value_id:c.postingTypeReferenceValueId,p_posting_reference:c.postingReference,p_posting_sequence:c.postingSequence,p_posted_at:c.postedAt,p_currency_code:c.currencyCode,p_debit_account_code:c.debitAccountCode,p_credit_account_code:c.creditAccountCode,p_amount:c.amount,p_description:c.description ?? null,p_actor_user_id:c.actorUserId })); }

  async createBankStatementLine(c: CreateBankStatementLineCommand): Promise<string> { await this.allow(c); this.assertBankAmounts(c.creditAmount,c.debitAmount); return this.command(() => this.repository.createBankStatementLine({ p_financial_bank_statement_line_id:randomUUID(),p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_bank_transaction_reference:c.bankTransactionReference,p_bank_account_reference:c.bankAccountReference,p_transaction_at:c.transactionAt,p_value_date:c.valueDate ?? null,p_currency_code:c.currencyCode,p_credit_amount:c.creditAmount,p_debit_amount:c.debitAmount,p_narration:c.narration ?? null,p_bank_match_status_reference_value_id:c.bankMatchStatusReferenceValueId,p_actor_user_id:c.actorUserId })); }
  async createBankMatch(c: CreateBankMatchCommand): Promise<string> { await this.allow(c); if (!Number.isFinite(c.matchedAmount) || c.matchedAmount <= 0) throw new BadRequestException('Bank Match amount must be greater than zero.'); return this.command(() => this.repository.createBankMatch({ p_financial_bank_match_id:randomUUID(),p_organization_id:c.organizationId,p_hospital_id:c.hospitalId,p_financial_bank_statement_line_id:c.financialBankStatementLineId,p_financial_remittance_batch_id:c.financialRemittanceBatchId ?? null,p_financial_claim_settlement_id:c.financialClaimSettlementId ?? null,p_bank_match_status_reference_value_id:c.bankMatchStatusReferenceValueId,p_matched_amount:c.matchedAmount,p_matched_at:c.matchedAt,p_notes:c.notes ?? null,p_actor_user_id:c.actorUserId })); }

  private async allow(c: FinancialCommandContext): Promise<void> { await this.access.assertCommandAccess(c.actorUserId,c.organizationId,c.hospitalId); }
  private async requireBatch(c: FinancialCommandContext & { financialRemittanceBatchId: string }): Promise<FinancialRemittanceBatch> { const batch=await this.repository.findActiveRemittanceBatchById(c.organizationId,c.hospitalId,c.financialRemittanceBatchId); if (!batch) throw new NotFoundException('Remittance Batch was not found.'); return batch; }
  private domain<T>(operation: () => T): T { try { return operation(); } catch(error) { if(error instanceof FinancialDomainError) throw new BadRequestException(error.message); throw error; } }
  private async command(op: () => Promise<string>): Promise<string> { try { return await op(); } catch(error) { const code=(error as { code?: string }).code; if(code==='23505') throw new ConflictException('A Financial record with the same active business reference already exists.'); if(code==='23503') throw new BadRequestException('A required Financial dependency is unavailable.'); throw error; } }
  private assertBankAmounts(credit:number,debit:number): void { if(!Number.isFinite(credit)||!Number.isFinite(debit)||credit<0||debit<0||(credit===0&&debit===0)||(credit>0&&debit>0)) throw new BadRequestException('Exactly one Bank Statement amount must be greater than zero.'); }
}
