BEGIN;

-- Phase 9 Financial Management command persistence.
-- UUID identities are generated by the NestJS application layer.
DO $$
BEGIN
  IF to_regclass('public.financial_remittance_batch') IS NULL
     OR to_regclass('public.financial_claim_settlement') IS NULL
     OR to_regclass('public.financial_recovery') IS NULL
     OR to_regclass('public.financial_posting') IS NULL
     OR to_regclass('public.financial_bank_match') IS NULL THEN
    RAISE EXCEPTION 'Phase 9 Financial Management command functions require the approved Financial Management schema.';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.assert_financial_active_actor(p_actor_user_id UUID)
RETURNS VOID LANGUAGE plpgsql STABLE AS $$
BEGIN
  IF p_actor_user_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.users actor
    WHERE actor.id = p_actor_user_id
      AND LOWER(COALESCE(actor.status, '')) = 'active'
      AND COALESCE(actor.is_deleted, FALSE) = FALSE
  ) THEN RAISE EXCEPTION 'Financial command actor must be an active IAM User.'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.assert_financial_hospital_scope(p_organization_id UUID, p_hospital_id UUID)
RETURNS VOID LANGUAGE plpgsql STABLE AS $$
BEGIN
  IF p_organization_id IS NULL OR p_hospital_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.hospitals hospital
    WHERE hospital.id = p_hospital_id AND hospital.organization_id = p_organization_id
      AND hospital.deleted_at IS NULL AND COALESCE(hospital.is_deleted, FALSE) = FALSE
  ) THEN RAISE EXCEPTION 'Financial Hospital must be active and belong to the requested Organization.'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.assert_financial_reference_value(p_reference_value_id UUID, p_category_code TEXT)
RETURNS VOID LANGUAGE plpgsql STABLE AS $$
BEGIN
  IF p_reference_value_id IS NULL OR BTRIM(COALESCE(p_category_code, '')) = '' OR NOT EXISTS (
    SELECT 1 FROM public.reference_values value
    JOIN public.reference_categories category ON category.id = value.category_id
    WHERE value.id = p_reference_value_id AND category.code = p_category_code
      AND value.organization_id IS NULL AND value.is_active = TRUE
      AND value.deleted_at IS NULL AND COALESCE(value.is_deleted, FALSE) = FALSE
  ) THEN RAISE EXCEPTION 'Financial Reference Data value is invalid for category %.', p_category_code; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_remittance_batch(
  p_financial_remittance_batch_id UUID, p_organization_id UUID, p_hospital_id UUID,
  p_insurance_partner_id UUID, p_claim_product_reference_value_id UUID,
  p_remittance_source_type_reference_value_id UUID, p_remittance_status_reference_value_id UUID,
  p_remittance_reference VARCHAR, p_received_at TIMESTAMPTZ, p_currency_code CHAR(3),
  p_gross_amount NUMERIC, p_net_amount NUMERIC, p_external_reference VARCHAR, p_notes TEXT,
  p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id);
  PERFORM public.assert_financial_hospital_scope(p_organization_id, p_hospital_id);
  PERFORM public.assert_financial_reference_value(p_claim_product_reference_value_id, 'CLAIM_PRODUCT');
  PERFORM public.assert_financial_reference_value(p_remittance_source_type_reference_value_id, 'FINANCIAL_REMITTANCE_SOURCE_TYPE');
  PERFORM public.assert_financial_reference_value(p_remittance_status_reference_value_id, 'FINANCIAL_REMITTANCE_STATUS');
  IF p_financial_remittance_batch_id IS NULL OR BTRIM(COALESCE(p_remittance_reference, '')) = '' OR p_received_at IS NULL OR p_gross_amount IS NULL OR p_net_amount IS NULL OR p_gross_amount < 0 OR p_net_amount < 0 OR p_net_amount > p_gross_amount OR BTRIM(COALESCE(p_currency_code, '')) !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'Financial Remittance Batch identity, reference, received time, uppercase currency, and valid amounts are required.'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.insurance_entities partner WHERE partner.id=p_insurance_partner_id AND partner.deleted_at IS NULL AND COALESCE(partner.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Remittance Batch Insurance Partner must be active.'; END IF;
  INSERT INTO public.financial_remittance_batch(financial_remittance_batch_id,organization_id,hospital_id,insurance_partner_id,claim_product_reference_value_id,remittance_source_type_reference_value_id,remittance_status_reference_value_id,remittance_reference,received_at,currency_code,gross_amount,net_amount,external_reference,notes,created_by,created_at,updated_by,updated_at,version)
  VALUES(p_financial_remittance_batch_id,p_organization_id,p_hospital_id,p_insurance_partner_id,p_claim_product_reference_value_id,p_remittance_source_type_reference_value_id,p_remittance_status_reference_value_id,BTRIM(p_remittance_reference),p_received_at,UPPER(BTRIM(p_currency_code)),p_gross_amount,p_net_amount,NULLIF(BTRIM(p_external_reference),''),NULLIF(BTRIM(p_notes),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_remittance_batch_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_remittance_line_item(
  p_financial_remittance_line_item_id UUID,p_financial_remittance_batch_id UUID,p_organization_id UUID,p_hospital_id UUID,p_claim_id UUID,p_line_status_reference_value_id UUID,p_payer_claim_reference VARCHAR,p_line_reference VARCHAR,p_gross_amount NUMERIC,p_deduction_amount NUMERIC,p_net_amount NUMERIC,p_currency_code CHAR(3),p_received_payload_summary JSONB,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_line_status_reference_value_id,'FINANCIAL_REMITTANCE_LINE_STATUS');
  IF p_financial_remittance_line_item_id IS NULL OR BTRIM(COALESCE(p_line_reference,''))='' OR p_gross_amount IS NULL OR p_deduction_amount IS NULL OR p_net_amount IS NULL OR p_gross_amount<0 OR p_deduction_amount<0 OR p_net_amount<0 OR p_net_amount>p_gross_amount OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'Financial Remittance Line identity, reference, uppercase currency, and valid amounts are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.financial_remittance_batch batch WHERE batch.financial_remittance_batch_id=p_financial_remittance_batch_id AND batch.organization_id=p_organization_id AND batch.hospital_id=p_hospital_id AND batch.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Remittance Line Batch must be active and tenant scoped.'; END IF;
  IF p_claim_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.claims claim WHERE claim.id=p_claim_id AND claim.organization_id=p_organization_id AND claim.hospital_id=p_hospital_id AND claim.deleted_at IS NULL AND COALESCE(claim.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Remittance Line Claim must be active and tenant scoped.'; END IF;
  INSERT INTO public.financial_remittance_line_item(financial_remittance_line_item_id,financial_remittance_batch_id,organization_id,hospital_id,claim_id,line_status_reference_value_id,payer_claim_reference,line_reference,gross_amount,deduction_amount,net_amount,currency_code,received_payload_summary,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_remittance_line_item_id,p_financial_remittance_batch_id,p_organization_id,p_hospital_id,p_claim_id,p_line_status_reference_value_id,NULLIF(BTRIM(p_payer_claim_reference),''),BTRIM(p_line_reference),p_gross_amount,p_deduction_amount,p_net_amount,UPPER(BTRIM(p_currency_code)),p_received_payload_summary,p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_remittance_line_item_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_remittance_evidence(
  p_financial_remittance_evidence_id UUID,p_financial_remittance_batch_id UUID,p_organization_id UUID,p_hospital_id UUID,p_storage_object_reference VARCHAR,p_file_name VARCHAR,p_mime_type VARCHAR,p_file_size_bytes BIGINT,p_document_hash VARCHAR,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id);
  IF p_financial_remittance_evidence_id IS NULL OR BTRIM(COALESCE(p_storage_object_reference,''))='' OR BTRIM(COALESCE(p_file_name,''))='' OR COALESCE(p_file_size_bytes,0)<0 THEN RAISE EXCEPTION 'Financial Remittance Evidence identity, storage reference, file name, and valid file size are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.financial_remittance_batch batch WHERE batch.financial_remittance_batch_id=p_financial_remittance_batch_id AND batch.organization_id=p_organization_id AND batch.hospital_id=p_hospital_id AND batch.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Remittance Evidence Batch must be active and tenant scoped.'; END IF;
  INSERT INTO public.financial_remittance_evidence(financial_remittance_evidence_id,financial_remittance_batch_id,organization_id,hospital_id,storage_object_reference,file_name,mime_type,file_size_bytes,document_hash,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_remittance_evidence_id,p_financial_remittance_batch_id,p_organization_id,p_hospital_id,BTRIM(p_storage_object_reference),BTRIM(p_file_name),NULLIF(BTRIM(p_mime_type),''),p_file_size_bytes,NULLIF(BTRIM(p_document_hash),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_remittance_evidence_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_claim_settlement(
  p_financial_claim_settlement_id UUID,p_organization_id UUID,p_hospital_id UUID,p_claim_id UUID,p_insurance_partner_id UUID,p_financial_remittance_line_item_id UUID,p_claim_product_reference_value_id UUID,p_settlement_status_reference_value_id UUID,p_settlement_reference VARCHAR,p_payer_settlement_reference VARCHAR,p_settled_at TIMESTAMPTZ,p_currency_code CHAR(3),p_gross_payer_paid_amount NUMERIC,p_tds_amount NUMERIC,p_payer_deduction_amount NUMERIC,p_other_payer_adjustment_amount NUMERIC,p_net_payer_settlement_amount NUMERIC,p_patient_responsibility_amount NUMERIC,p_hospital_write_off_amount NUMERIC,p_notes TEXT,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_claim_product_reference_value_id,'CLAIM_PRODUCT'); PERFORM public.assert_financial_reference_value(p_settlement_status_reference_value_id,'FINANCIAL_SETTLEMENT_STATUS');
  IF p_financial_claim_settlement_id IS NULL OR BTRIM(COALESCE(p_settlement_reference,''))='' OR p_settled_at IS NULL OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' OR LEAST(COALESCE(p_gross_payer_paid_amount,-1),COALESCE(p_tds_amount,-1),COALESCE(p_payer_deduction_amount,-1),COALESCE(p_other_payer_adjustment_amount,-1),COALESCE(p_net_payer_settlement_amount,-1),COALESCE(p_patient_responsibility_amount,-1),COALESCE(p_hospital_write_off_amount,-1))<0 THEN RAISE EXCEPTION 'Financial Settlement identity, reference, date, uppercase currency, and non-negative amounts are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.claims claim WHERE claim.id=p_claim_id AND claim.organization_id=p_organization_id AND claim.hospital_id=p_hospital_id AND claim.deleted_at IS NULL AND COALESCE(claim.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Settlement Claim must be active and tenant scoped.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.insurance_entities partner WHERE partner.id=p_insurance_partner_id AND partner.deleted_at IS NULL AND COALESCE(partner.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Settlement Insurance Partner must be active.'; END IF;
  IF p_financial_remittance_line_item_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_remittance_line_item line WHERE line.financial_remittance_line_item_id=p_financial_remittance_line_item_id AND line.organization_id=p_organization_id AND line.hospital_id=p_hospital_id AND line.claim_id=p_claim_id AND line.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Settlement Remittance Line must be active, tenant scoped, and linked to the Claim.'; END IF;
  INSERT INTO public.financial_claim_settlement(financial_claim_settlement_id,organization_id,hospital_id,claim_id,insurance_partner_id,financial_remittance_line_item_id,claim_product_reference_value_id,settlement_status_reference_value_id,settlement_reference,payer_settlement_reference,settled_at,currency_code,gross_payer_paid_amount,tds_amount,payer_deduction_amount,other_payer_adjustment_amount,net_payer_settlement_amount,patient_responsibility_amount,hospital_write_off_amount,notes,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_claim_settlement_id,p_organization_id,p_hospital_id,p_claim_id,p_insurance_partner_id,p_financial_remittance_line_item_id,p_claim_product_reference_value_id,p_settlement_status_reference_value_id,BTRIM(p_settlement_reference),NULLIF(BTRIM(p_payer_settlement_reference),''),p_settled_at,UPPER(BTRIM(p_currency_code)),p_gross_payer_paid_amount,p_tds_amount,p_payer_deduction_amount,p_other_payer_adjustment_amount,p_net_payer_settlement_amount,p_patient_responsibility_amount,p_hospital_write_off_amount,NULLIF(BTRIM(p_notes),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_claim_settlement_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_settlement_deduction(
  p_financial_settlement_deduction_id UUID,p_financial_claim_settlement_id UUID,p_organization_id UUID,p_hospital_id UUID,p_deduction_type_reference_value_id UUID,p_deduction_reference VARCHAR,p_description TEXT,p_amount NUMERIC,p_currency_code CHAR(3),p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_deduction_type_reference_value_id,'FINANCIAL_DEDUCTION_TYPE');
  IF p_financial_settlement_deduction_id IS NULL OR p_amount IS NULL OR p_amount<=0 OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'Financial Settlement Deduction identity, positive amount, and uppercase currency are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.financial_claim_settlement settlement WHERE settlement.financial_claim_settlement_id=p_financial_claim_settlement_id AND settlement.organization_id=p_organization_id AND settlement.hospital_id=p_hospital_id AND settlement.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Settlement Deduction parent must be active and tenant scoped.'; END IF;
  INSERT INTO public.financial_settlement_deduction(financial_settlement_deduction_id,financial_claim_settlement_id,organization_id,hospital_id,deduction_type_reference_value_id,deduction_reference,description,amount,currency_code,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_settlement_deduction_id,p_financial_claim_settlement_id,p_organization_id,p_hospital_id,p_deduction_type_reference_value_id,NULLIF(BTRIM(p_deduction_reference),''),NULLIF(BTRIM(p_description),''),p_amount,UPPER(BTRIM(p_currency_code)),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_settlement_deduction_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_recovery(
  p_financial_recovery_id UUID,p_organization_id UUID,p_hospital_id UUID,p_claim_id UUID,p_financial_claim_settlement_id UUID,p_insurance_partner_id UUID,p_claim_product_reference_value_id UUID,p_recovery_type_reference_value_id UUID,p_recovery_status_reference_value_id UUID,p_recovery_reference VARCHAR,p_opened_at TIMESTAMPTZ,p_due_at TIMESTAMPTZ,p_currency_code CHAR(3),p_original_amount NUMERIC,p_recovered_amount NUMERIC,p_outstanding_amount NUMERIC,p_notes TEXT,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_claim_product_reference_value_id,'CLAIM_PRODUCT'); PERFORM public.assert_financial_reference_value(p_recovery_type_reference_value_id,'FINANCIAL_RECOVERY_TYPE'); PERFORM public.assert_financial_reference_value(p_recovery_status_reference_value_id,'FINANCIAL_RECOVERY_STATUS');
  IF p_financial_recovery_id IS NULL OR BTRIM(COALESCE(p_recovery_reference,''))='' OR p_opened_at IS NULL OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' OR p_original_amount IS NULL OR p_recovered_amount IS NULL OR p_outstanding_amount IS NULL OR p_original_amount<0 OR p_recovered_amount<0 OR p_outstanding_amount<0 OR p_recovered_amount>p_original_amount OR p_outstanding_amount<>p_original_amount-p_recovered_amount THEN RAISE EXCEPTION 'Financial Recovery identity, reference, valid currency, and reconciled amounts are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.claims claim WHERE claim.id=p_claim_id AND claim.organization_id=p_organization_id AND claim.hospital_id=p_hospital_id AND claim.deleted_at IS NULL AND COALESCE(claim.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Recovery Claim must be active and tenant scoped.'; END IF;
  IF p_financial_claim_settlement_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_claim_settlement settlement WHERE settlement.financial_claim_settlement_id=p_financial_claim_settlement_id AND settlement.organization_id=p_organization_id AND settlement.hospital_id=p_hospital_id AND settlement.claim_id=p_claim_id AND settlement.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Recovery Settlement must be active, tenant scoped, and linked to the Claim.'; END IF;
  INSERT INTO public.financial_recovery(financial_recovery_id,organization_id,hospital_id,claim_id,financial_claim_settlement_id,insurance_partner_id,claim_product_reference_value_id,recovery_type_reference_value_id,recovery_status_reference_value_id,recovery_reference,opened_at,due_at,currency_code,original_amount,recovered_amount,outstanding_amount,notes,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_recovery_id,p_organization_id,p_hospital_id,p_claim_id,p_financial_claim_settlement_id,p_insurance_partner_id,p_claim_product_reference_value_id,p_recovery_type_reference_value_id,p_recovery_status_reference_value_id,BTRIM(p_recovery_reference),p_opened_at,p_due_at,UPPER(BTRIM(p_currency_code)),p_original_amount,p_recovered_amount,p_outstanding_amount,NULLIF(BTRIM(p_notes),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_recovery_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_posting(
  p_financial_posting_id UUID,p_organization_id UUID,p_hospital_id UUID,p_claim_id UUID,p_financial_claim_settlement_id UUID,p_financial_recovery_id UUID,p_claim_product_reference_value_id UUID,p_posting_type_reference_value_id UUID,p_posting_reference UUID,p_posting_sequence INTEGER,p_posted_at TIMESTAMPTZ,p_currency_code CHAR(3),p_debit_account_code VARCHAR,p_credit_account_code VARCHAR,p_amount NUMERIC,p_description TEXT,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_claim_product_reference_value_id,'CLAIM_PRODUCT'); PERFORM public.assert_financial_reference_value(p_posting_type_reference_value_id,'FINANCIAL_POSTING_TYPE');
  IF p_financial_posting_id IS NULL OR p_posting_reference IS NULL OR COALESCE(p_posting_sequence,0)<1 OR p_posted_at IS NULL OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' OR BTRIM(COALESCE(p_debit_account_code,''))='' OR BTRIM(COALESCE(p_credit_account_code,''))='' OR BTRIM(p_debit_account_code)=BTRIM(p_credit_account_code) OR p_amount IS NULL OR p_amount<=0 OR ((p_financial_claim_settlement_id IS NOT NULL)::INTEGER+(p_financial_recovery_id IS NOT NULL)::INTEGER)<>1 THEN RAISE EXCEPTION 'Financial Posting identity, one target, accounts, positive amount, uppercase currency, and sequence are required.'; END IF;
  IF p_claim_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.claims claim WHERE claim.id=p_claim_id AND claim.organization_id=p_organization_id AND claim.hospital_id=p_hospital_id AND claim.deleted_at IS NULL AND COALESCE(claim.is_deleted,FALSE)=FALSE) THEN RAISE EXCEPTION 'Financial Posting Claim must be active and tenant scoped.'; END IF;
  IF p_financial_claim_settlement_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_claim_settlement settlement WHERE settlement.financial_claim_settlement_id=p_financial_claim_settlement_id AND settlement.organization_id=p_organization_id AND settlement.hospital_id=p_hospital_id AND (p_claim_id IS NULL OR settlement.claim_id=p_claim_id) AND settlement.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Posting Settlement target must be active and tenant scoped.'; END IF;
  IF p_financial_recovery_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_recovery recovery WHERE recovery.financial_recovery_id=p_financial_recovery_id AND recovery.organization_id=p_organization_id AND recovery.hospital_id=p_hospital_id AND (p_claim_id IS NULL OR recovery.claim_id=p_claim_id) AND recovery.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Posting Recovery target must be active and tenant scoped.'; END IF;
  INSERT INTO public.financial_posting(financial_posting_id,organization_id,hospital_id,claim_id,financial_claim_settlement_id,financial_recovery_id,claim_product_reference_value_id,posting_type_reference_value_id,posting_reference,posting_sequence,posted_at,currency_code,debit_account_code,credit_account_code,amount,description,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_posting_id,p_organization_id,p_hospital_id,p_claim_id,p_financial_claim_settlement_id,p_financial_recovery_id,p_claim_product_reference_value_id,p_posting_type_reference_value_id,p_posting_reference,p_posting_sequence,p_posted_at,UPPER(BTRIM(p_currency_code)),BTRIM(p_debit_account_code),BTRIM(p_credit_account_code),p_amount,NULLIF(BTRIM(p_description),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_posting_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_bank_statement_line(
  p_financial_bank_statement_line_id UUID,p_organization_id UUID,p_hospital_id UUID,p_bank_transaction_reference VARCHAR,p_bank_account_reference VARCHAR,p_transaction_at TIMESTAMPTZ,p_value_date DATE,p_currency_code CHAR(3),p_credit_amount NUMERIC,p_debit_amount NUMERIC,p_narration TEXT,p_bank_match_status_reference_value_id UUID,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_bank_match_status_reference_value_id,'FINANCIAL_BANK_MATCH_STATUS');
  IF p_financial_bank_statement_line_id IS NULL OR BTRIM(COALESCE(p_bank_transaction_reference,''))='' OR BTRIM(COALESCE(p_bank_account_reference,''))='' OR p_transaction_at IS NULL OR BTRIM(COALESCE(p_currency_code,'')) !~ '^[A-Z]{3}$' OR NOT ((COALESCE(p_credit_amount,0)>0 AND COALESCE(p_debit_amount,0)=0) OR (COALESCE(p_debit_amount,0)>0 AND COALESCE(p_credit_amount,0)=0)) THEN RAISE EXCEPTION 'Financial Bank Statement Line identity, references, transaction, uppercase currency, and exactly one positive direction are required.'; END IF;
  INSERT INTO public.financial_bank_statement_line(financial_bank_statement_line_id,organization_id,hospital_id,bank_transaction_reference,bank_account_reference,transaction_at,value_date,currency_code,credit_amount,debit_amount,narration,bank_match_status_reference_value_id,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_bank_statement_line_id,p_organization_id,p_hospital_id,BTRIM(p_bank_transaction_reference),BTRIM(p_bank_account_reference),p_transaction_at,p_value_date,UPPER(BTRIM(p_currency_code)),COALESCE(p_credit_amount,0),COALESCE(p_debit_amount,0),NULLIF(BTRIM(p_narration),''),p_bank_match_status_reference_value_id,p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_bank_statement_line_id;
END $$;

CREATE OR REPLACE FUNCTION public.create_financial_bank_match(
  p_financial_bank_match_id UUID,p_organization_id UUID,p_hospital_id UUID,p_financial_bank_statement_line_id UUID,p_financial_remittance_batch_id UUID,p_financial_claim_settlement_id UUID,p_bank_match_status_reference_value_id UUID,p_matched_amount NUMERIC,p_matched_at TIMESTAMPTZ,p_notes TEXT,p_actor_user_id UUID
) RETURNS UUID LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.assert_financial_active_actor(p_actor_user_id); PERFORM public.assert_financial_hospital_scope(p_organization_id,p_hospital_id); PERFORM public.assert_financial_reference_value(p_bank_match_status_reference_value_id,'FINANCIAL_BANK_MATCH_STATUS');
  IF p_financial_bank_match_id IS NULL OR p_matched_amount IS NULL OR p_matched_amount<=0 OR p_matched_at IS NULL OR ((p_financial_remittance_batch_id IS NOT NULL)::INTEGER+(p_financial_claim_settlement_id IS NOT NULL)::INTEGER)<>1 THEN RAISE EXCEPTION 'Financial Bank Match identity, one target, positive amount, and match time are required.'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.financial_bank_statement_line line WHERE line.financial_bank_statement_line_id=p_financial_bank_statement_line_id AND line.organization_id=p_organization_id AND line.hospital_id=p_hospital_id AND line.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Bank Match statement line must be active and tenant scoped.'; END IF;
  IF p_financial_remittance_batch_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_remittance_batch batch WHERE batch.financial_remittance_batch_id=p_financial_remittance_batch_id AND batch.organization_id=p_organization_id AND batch.hospital_id=p_hospital_id AND batch.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Bank Match Batch target must be active and tenant scoped.'; END IF;
  IF p_financial_claim_settlement_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_claim_settlement settlement WHERE settlement.financial_claim_settlement_id=p_financial_claim_settlement_id AND settlement.organization_id=p_organization_id AND settlement.hospital_id=p_hospital_id AND settlement.deleted_at IS NULL) THEN RAISE EXCEPTION 'Financial Bank Match Settlement target must be active and tenant scoped.'; END IF;
  INSERT INTO public.financial_bank_match(financial_bank_match_id,organization_id,hospital_id,financial_bank_statement_line_id,financial_remittance_batch_id,financial_claim_settlement_id,bank_match_status_reference_value_id,matched_amount,matched_at,notes,created_by,created_at,updated_by,updated_at,version) VALUES(p_financial_bank_match_id,p_organization_id,p_hospital_id,p_financial_bank_statement_line_id,p_financial_remittance_batch_id,p_financial_claim_settlement_id,p_bank_match_status_reference_value_id,p_matched_amount,p_matched_at,NULLIF(BTRIM(p_notes),''),p_actor_user_id,NOW(),p_actor_user_id,NOW(),1);
  RETURN p_financial_bank_match_id;
END $$;

COMMENT ON FUNCTION public.create_financial_posting IS 'Creates one immutable Phase 9 Financial Posting. Corrections require a future compensating posting, never mutation.';
COMMENT ON FUNCTION public.assert_financial_active_actor IS 'Internal Phase 9 command guard for an active ClaimNX IAM User.';
COMMENT ON FUNCTION public.assert_financial_hospital_scope IS 'Internal Phase 9 command guard for active Organization and Hospital scope.';
COMMENT ON FUNCTION public.assert_financial_reference_value IS 'Internal Phase 9 command guard for active global Financial Reference Data.';

COMMIT;
