BEGIN;

-- Phase 9 is additive. IDs are generated by the application layer.
DO $$ BEGIN
 IF to_regclass('public.organizations') IS NULL OR to_regclass('public.hospitals') IS NULL OR to_regclass('public.claims') IS NULL OR to_regclass('public.users') IS NULL OR to_regclass('public.insurance_entities') IS NULL OR to_regclass('public.reference_values') IS NULL THEN
   RAISE EXCEPTION 'Phase 9 requires Organization, Hospital, Claim, IAM, Insurance, and Reference Data tables.';
 END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.financial_remittance_batch (
 financial_remittance_batch_id UUID NOT NULL, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, insurance_partner_id UUID NOT NULL, claim_product_reference_value_id UUID NOT NULL, remittance_source_type_reference_value_id UUID NOT NULL, remittance_status_reference_value_id UUID NOT NULL, remittance_reference VARCHAR(100) NOT NULL, received_at TIMESTAMPTZ NOT NULL, currency_code CHAR(3) NOT NULL, gross_amount NUMERIC(19,4) NOT NULL, net_amount NUMERIC(19,4) NOT NULL, external_reference VARCHAR(255), notes TEXT, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT pk_financial_remittance_batch PRIMARY KEY(financial_remittance_batch_id), CONSTRAINT ck_financial_remittance_batch_version CHECK(version>=1), CONSTRAINT ck_financial_remittance_batch_currency CHECK(currency_code~'^[A-Z]{3}$'), CONSTRAINT ck_financial_remittance_batch_amounts CHECK(gross_amount>=0 AND net_amount>=0 AND net_amount<=gross_amount), CONSTRAINT fk_financial_remittance_batch_organization FOREIGN KEY(organization_id) REFERENCES public.organizations(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_batch_hospital FOREIGN KEY(hospital_id) REFERENCES public.hospitals(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_batch_partner FOREIGN KEY(insurance_partner_id) REFERENCES public.insurance_entities(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_batch_created_by FOREIGN KEY(created_by) REFERENCES public.users(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_batch_updated_by FOREIGN KEY(updated_by) REFERENCES public.users(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_batch_deleted_by FOREIGN KEY(deleted_by) REFERENCES public.users(id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS public.financial_remittance_line_item (
 financial_remittance_line_item_id UUID NOT NULL, financial_remittance_batch_id UUID NOT NULL, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, claim_id UUID, line_status_reference_value_id UUID NOT NULL, payer_claim_reference VARCHAR(100), line_reference VARCHAR(100) NOT NULL, gross_amount NUMERIC(19,4) NOT NULL, deduction_amount NUMERIC(19,4) NOT NULL DEFAULT 0, net_amount NUMERIC(19,4) NOT NULL, currency_code CHAR(3) NOT NULL, received_payload_summary JSONB, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT pk_financial_remittance_line_item PRIMARY KEY(financial_remittance_line_item_id), CONSTRAINT ck_financial_remittance_line_item_version CHECK(version>=1), CONSTRAINT ck_financial_remittance_line_item_amounts CHECK(gross_amount>=0 AND deduction_amount>=0 AND net_amount>=0 AND net_amount<=gross_amount), CONSTRAINT fk_financial_remittance_line_item_batch FOREIGN KEY(financial_remittance_batch_id) REFERENCES public.financial_remittance_batch(financial_remittance_batch_id) ON DELETE RESTRICT, CONSTRAINT fk_financial_remittance_line_item_claim FOREIGN KEY(claim_id) REFERENCES public.claims(id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS public.financial_remittance_evidence (financial_remittance_evidence_id UUID PRIMARY KEY, financial_remittance_batch_id UUID NOT NULL REFERENCES public.financial_remittance_batch(financial_remittance_batch_id) ON DELETE RESTRICT, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, storage_object_reference VARCHAR(512) NOT NULL, file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100), file_size_bytes BIGINT NOT NULL DEFAULT 0 CHECK(file_size_bytes>=0), document_hash VARCHAR(128), created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1));

CREATE TABLE IF NOT EXISTS public.financial_claim_settlement (
 financial_claim_settlement_id UUID NOT NULL, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, claim_id UUID NOT NULL, insurance_partner_id UUID NOT NULL, financial_remittance_line_item_id UUID, claim_product_reference_value_id UUID NOT NULL, settlement_status_reference_value_id UUID NOT NULL, settlement_reference VARCHAR(100) NOT NULL, payer_settlement_reference VARCHAR(100), settled_at TIMESTAMPTZ NOT NULL, currency_code CHAR(3) NOT NULL, gross_payer_paid_amount NUMERIC(19,4) NOT NULL, tds_amount NUMERIC(19,4) NOT NULL DEFAULT 0, payer_deduction_amount NUMERIC(19,4) NOT NULL DEFAULT 0, other_payer_adjustment_amount NUMERIC(19,4) NOT NULL DEFAULT 0, net_payer_settlement_amount NUMERIC(19,4) NOT NULL, patient_responsibility_amount NUMERIC(19,4) NOT NULL DEFAULT 0, hospital_write_off_amount NUMERIC(19,4) NOT NULL DEFAULT 0, notes TEXT, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1,
 CONSTRAINT pk_financial_claim_settlement PRIMARY KEY(financial_claim_settlement_id), CONSTRAINT ck_financial_claim_settlement_version CHECK(version>=1), CONSTRAINT ck_financial_claim_settlement_amounts CHECK(gross_payer_paid_amount>=0 AND tds_amount>=0 AND payer_deduction_amount>=0 AND other_payer_adjustment_amount>=0 AND net_payer_settlement_amount>=0 AND patient_responsibility_amount>=0 AND hospital_write_off_amount>=0), CONSTRAINT fk_financial_claim_settlement_claim FOREIGN KEY(claim_id) REFERENCES public.claims(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_claim_settlement_partner FOREIGN KEY(insurance_partner_id) REFERENCES public.insurance_entities(id) ON DELETE RESTRICT, CONSTRAINT fk_financial_claim_settlement_line FOREIGN KEY(financial_remittance_line_item_id) REFERENCES public.financial_remittance_line_item(financial_remittance_line_item_id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS public.financial_settlement_deduction (financial_settlement_deduction_id UUID PRIMARY KEY, financial_claim_settlement_id UUID NOT NULL REFERENCES public.financial_claim_settlement(financial_claim_settlement_id) ON DELETE RESTRICT, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, deduction_type_reference_value_id UUID NOT NULL, deduction_reference VARCHAR(100), description TEXT, amount NUMERIC(19,4) NOT NULL CHECK(amount>0), currency_code CHAR(3) NOT NULL, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1));
CREATE TABLE IF NOT EXISTS public.financial_recovery (financial_recovery_id UUID PRIMARY KEY, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, claim_id UUID NOT NULL REFERENCES public.claims(id) ON DELETE RESTRICT, financial_claim_settlement_id UUID REFERENCES public.financial_claim_settlement(financial_claim_settlement_id) ON DELETE RESTRICT, insurance_partner_id UUID NOT NULL REFERENCES public.insurance_entities(id) ON DELETE RESTRICT, claim_product_reference_value_id UUID NOT NULL, recovery_type_reference_value_id UUID NOT NULL, recovery_status_reference_value_id UUID NOT NULL, recovery_reference VARCHAR(100) NOT NULL, opened_at TIMESTAMPTZ NOT NULL, due_at TIMESTAMPTZ, currency_code CHAR(3) NOT NULL, original_amount NUMERIC(19,4) NOT NULL, recovered_amount NUMERIC(19,4) NOT NULL DEFAULT 0, outstanding_amount NUMERIC(19,4) NOT NULL, notes TEXT, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1), CONSTRAINT ck_financial_recovery_amounts CHECK(original_amount>=0 AND recovered_amount>=0 AND outstanding_amount>=0 AND recovered_amount<=original_amount));

CREATE TABLE IF NOT EXISTS public.financial_posting (financial_posting_id UUID PRIMARY KEY, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, claim_id UUID REFERENCES public.claims(id) ON DELETE RESTRICT, financial_claim_settlement_id UUID REFERENCES public.financial_claim_settlement(financial_claim_settlement_id) ON DELETE RESTRICT, financial_recovery_id UUID REFERENCES public.financial_recovery(financial_recovery_id) ON DELETE RESTRICT, claim_product_reference_value_id UUID NOT NULL, posting_type_reference_value_id UUID NOT NULL, posting_reference UUID NOT NULL, posting_sequence INTEGER NOT NULL, posted_at TIMESTAMPTZ NOT NULL, currency_code CHAR(3) NOT NULL, debit_account_code VARCHAR(50) NOT NULL, credit_account_code VARCHAR(50) NOT NULL, amount NUMERIC(19,4) NOT NULL, description TEXT, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1, CONSTRAINT ck_financial_posting_amount CHECK(amount>0), CONSTRAINT ck_financial_posting_accounts CHECK(debit_account_code<>credit_account_code), CONSTRAINT ck_financial_posting_version CHECK(version=1));

CREATE TABLE IF NOT EXISTS public.financial_bank_statement_line (financial_bank_statement_line_id UUID PRIMARY KEY, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, bank_transaction_reference VARCHAR(100) NOT NULL, bank_account_reference VARCHAR(100) NOT NULL, transaction_at TIMESTAMPTZ NOT NULL, value_date DATE, currency_code CHAR(3) NOT NULL, credit_amount NUMERIC(19,4) NOT NULL DEFAULT 0, debit_amount NUMERIC(19,4) NOT NULL DEFAULT 0, narration TEXT, bank_match_status_reference_value_id UUID NOT NULL, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1), CONSTRAINT ck_financial_bank_statement_line_amount CHECK((credit_amount>0 AND debit_amount=0) OR (debit_amount>0 AND credit_amount=0)));
CREATE TABLE IF NOT EXISTS public.financial_bank_match (financial_bank_match_id UUID PRIMARY KEY, organization_id UUID NOT NULL, hospital_id UUID NOT NULL, financial_bank_statement_line_id UUID NOT NULL REFERENCES public.financial_bank_statement_line(financial_bank_statement_line_id) ON DELETE RESTRICT, financial_remittance_batch_id UUID REFERENCES public.financial_remittance_batch(financial_remittance_batch_id) ON DELETE RESTRICT, financial_claim_settlement_id UUID REFERENCES public.financial_claim_settlement(financial_claim_settlement_id) ON DELETE RESTRICT, bank_match_status_reference_value_id UUID NOT NULL, matched_amount NUMERIC(19,4) NOT NULL CHECK(matched_amount>0), matched_at TIMESTAMPTZ NOT NULL, notes TEXT, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_by UUID, deleted_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1), CONSTRAINT ck_financial_bank_match_target CHECK((financial_remittance_batch_id IS NOT NULL)::INTEGER + (financial_claim_settlement_id IS NOT NULL)::INTEGER = 1));

-- Apply common tenant and audit foreign keys consistently to every Phase 9 table.
DO $$
DECLARE table_name TEXT; columns TEXT[]; column_name TEXT; target_table TEXT; constraint_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['financial_remittance_batch','financial_remittance_line_item','financial_remittance_evidence','financial_claim_settlement','financial_settlement_deduction','financial_recovery','financial_posting','financial_bank_statement_line','financial_bank_match'] LOOP
    FOREACH column_name IN ARRAY ARRAY['organization_id','hospital_id','created_by','updated_by','deleted_by'] LOOP
      target_table := CASE column_name WHEN 'organization_id' THEN 'organizations' WHEN 'hospital_id' THEN 'hospitals' ELSE 'users' END;
      constraint_name := format('fk_%s_%s', table_name, regexp_replace(column_name, '_id$', ''));
      IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=format('public.%I',table_name)::regclass AND conname=constraint_name) THEN
        EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES public.%I(id) ON DELETE RESTRICT',table_name,constraint_name,column_name,target_table);
      END IF;
    END LOOP;
  END LOOP;
END $$;

-- PostgreSQL assigns default names to inline primary keys. Rename them so all
-- Phase 9 primary-key constraints follow the ClaimNX `pk_<table>` convention.
DO $$
DECLARE
  table_name TEXT;
  old_constraint_name TEXT;
  new_constraint_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'financial_remittance_evidence',
    'financial_settlement_deduction',
    'financial_recovery',
    'financial_posting',
    'financial_bank_statement_line',
    'financial_bank_match'
  ] LOOP
    old_constraint_name := table_name || '_pkey';
    new_constraint_name := 'pk_' || table_name;

    IF EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conrelid = format('public.%I', table_name)::regclass
        AND conname = old_constraint_name
    ) AND NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conrelid = format('public.%I', table_name)::regclass
        AND conname = new_constraint_name
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I RENAME CONSTRAINT %I TO %I',
        table_name,
        old_constraint_name,
        new_constraint_name
      );
    END IF;
  END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_remittance_batch_org_partner_reference_active ON public.financial_remittance_batch(organization_id,insurance_partner_id,remittance_reference) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_remittance_line_item_batch_line_reference_active ON public.financial_remittance_line_item(financial_remittance_batch_id,line_reference) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_remittance_evidence_batch_storage_active ON public.financial_remittance_evidence(financial_remittance_batch_id,storage_object_reference) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_claim_settlement_org_reference_active ON public.financial_claim_settlement(organization_id,settlement_reference) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_recovery_org_reference_active ON public.financial_recovery(organization_id,recovery_reference) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_financial_bank_line_org_account_reference_active ON public.financial_bank_statement_line(organization_id,bank_account_reference,bank_transaction_reference) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_financial_settlement_claim_active ON public.financial_claim_settlement(organization_id,hospital_id,claim_id,settled_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_financial_recovery_claim_active ON public.financial_recovery(organization_id,hospital_id,claim_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_financial_posting_claim_posted_at ON public.financial_posting(organization_id,hospital_id,claim_id,posted_at DESC);

COMMIT;
